# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          The Poole style
url:              snowdj.github.io/poole
paginate:         1

author:
  name:           snowdj
  url:            https://twitter.com/snowdj
  email:          snowdj@gmail.com

# add a navigation bar at the top of the website with links to the About page, Archive page, and the feed. To do this, I modified the file _config.yml to define a dictionary of pages to show in my header
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'



# Custom vars
version:          1.0.0
github:
  repo:           http://snowdj.github.io/poole/
