# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'Everygreen <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://github.com/snowdj

author:
  name:           'snowdj'
  url:            https://twitter.com/snowdj

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/snowdj